- hosts: ansible_host
  become: true

  pre_tasks:
  - name: get EC2 facts
    ec2_metadata_facts:
    ignore_errors: true

  roles:
#    - { role: machine, node_type: controlbox_node, tags: ['controlbox'] }
    - { role: ssh-users, tags: ['users'] }
    - { role: ansible, tags: ['controlbox_ansible'] }
    - { role: git, tags: ['controlbox_git'] }